#include<iostream>
#include<string>
#include<map>
#include<vector>
#include<sstream>
using namespace std;

int main(){
    string input;
    while(cin>>input){
        map<int,string> map1;
        vector<vector<string>> holding(26);
        for(auto i=input.begin();i!=input.end();i++){
            string bak1;
            if(is)
                if(isupper(*i)) bak1 = tolower(*i);
                else if(islower(*i)) bak1 = *i;

        }
    }

}